// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  asymmetrical_grid: dynamic(() => import("./AsymmetricalGrid")),
  centered_statement: dynamic(() => import("./CenteredStatement")),
  contact_info_social_language: dynamic(
    () => import("./ContactInfoSocialLanguage"),
  ),
  featured_card: dynamic(() => import("./FeaturedCard")),
  gallery_overview: dynamic(() => import("./GalleryOverview")),
  headline_with_subtext: dynamic(() => import("./HeadlineWithSubtext")),
  hero_section: dynamic(() => import("./HeroSection")),
  highlighted_heading_side_content: dynamic(
    () => import("./HighlightedHeadingSideContent"),
  ),
  icon_text_grid: dynamic(() => import("./IconTextGrid")),
  interactive_card_sphere: dynamic(() => import("./InteractiveCardSphere")),
  intro_text_cta: dynamic(() => import("./IntroTextCta")),
  side_media_content: dynamic(() => import("./SideMediaContent")),
  testimonial_carousel: dynamic(() => import("./TestimonialCarousel")),
};
